apiVersion: v1
kind: Service
metadata:
  name: {{ template "springboot-helm.full_name" . }}
  labels:
    {{- include "springboot-helm.release_labels" . | indent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.ServiceType | quote }}
  ports:
    - port: {{.Values.ServicePort}}
      targetPort: {{.Values.ContainerPort}}
      protocol: TCP
  selector:
    app: {{ template "springboot-helm.full_name" . }}
